"""Initial Migration

Revision ID: 85a7c603de4b
Revises: 4b226c57d71c
Create Date: 2018-09-16 13:53:27.942561

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85a7c603de4b'
down_revision = '4b226c57d71c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('title', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'title')
    # ### end Alembic commands ###
